#!/bin/bash
#
# Example usage:
#   $ curlt http://www.google.com
#   $ time curlt http://www.google.com -v

set -e

curl_format='{
 "time_namelookup": %{time_namelookup}s,
 "time_connect": %{time_connect}s,
 "time_appconnect": %{time_appconnect}s,
 "time_pretransfer": %{time_pretransfer}s,
 "time_redirect": %{time_redirect}s,
 "time_starttransfer": %{time_starttransfer}s,
 "time_total": %{time_total}s
}'

exec curl -w "$curl_format" -o /dev/null -s "$@"
